---
title: "Summary Report"
author: "Author"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(MATSS)
library(dplyr)
library(ggplot2)
library(drake)
```

## Aggregate

```{r read all lin} 

loadd(all_lin)

```

```{r slope and p hists}

all_lin <- all_lin %>%
  mutate(signif = p <= .05,
         win = slope > 0,
         lose = slope < 0)

ggplot(all_lin, aes(x = slope)) +
  geom_histogram(alpha = .8) + theme_bw() + 
 # geom_density(alpha = 0) +
  facet_wrap(vars(currency), scales = "free_y") +
  geom_vline(xintercept = 0)


ggplot(all_lin, aes(x = slope)) +
  geom_histogram() + theme_bw() + 
  facet_wrap(vars(currency, signif), scales = "free_y", ncol = 2) 
# 
# ggplot(all_lin, aes(x = slope, y = p, size = r2)) +
#   geom_point() + theme_bw() + 
#   geom_hline(yintercept = .05) +
#   facet_wrap(vars(currency))
```

```{r summary table}
lin_sum <- all_lin %>%
  group_by(currency, signif) %>%
  summarize(prop_win = mean(win),
            prop_lose = mean(lose),
            n = dplyr::n()) %>%
  ungroup() %>%
  group_by(currency) %>%
  mutate(prop_overall = n / sum(n)) %>%
  ungroup()

print(lin_sum)

```

Run with 100 communities,

* About 50% of slopes are significantly different from zero
* Of those that are significantly different from zero, 70% are decreasing and 30% increasing. 

## Populations

```{r load pop}

loadd(all_pop_lin)


all_pop_lin <- all_pop_lin %>%
  mutate(signif = p <= .05,
         win = slope > 0,
         lose = slope < 0)

ggplot(all_pop_lin, aes(x = slope)) +
  geom_histogram() + theme_bw() + 
  geom_density(alpha = 0) +
  facet_wrap(vars(currency), scales = "free_y")


ggplot(all_pop_lin, aes(x = slope)) +
  geom_histogram() + theme_bw() + 
  facet_wrap(vars(currency, signif), scales = "free_y", ncol = 2)

# 
# ggplot(all_pop_lin, aes(x = slope, y = p, size = r2)) +
#   geom_point() + theme_bw() + 
#   geom_hline(yintercept = .05) +
#   facet_wrap(vars(currency), scales = "free_y")

lin_pop_sum <- all_pop_lin %>%
  group_by(currency, signif) %>%
  summarize(prop_win = mean(win),
            prop_lose = mean(lose),
            n = dplyr::n()) %>%
  ungroup() %>%
  group_by(currency) %>%
  mutate(prop_overall = n / sum(n)) %>%
  ungroup()

print(lin_pop_sum)


```

Run with 100 communities,

- 75% of slopes are nonsignificant
- Of those that are significant, 43% are increasing and 57% are decreasing. 
